import swaggerJsdoc from "swagger-jsdoc";

const options = {
    apis: ['**/routes/rest/controllers/**/index.ts','**/routes/rest/controllers/**/index.js'],
    basePath: '/',
    swaggerDefinition: {
        info: {
            description: 'Test API with autogenerated swagger doc',
            swagger: '2.0',
            title: 'POC API',
            version: '1.0.0',
        },
    },
};
const specs = swaggerJsdoc(options);

export default specs;
